# Generated by Django 2.0.6 on 2018-06-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries_Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country_rus', models.CharField(max_length=100, verbose_name='страна')),
                ('city_rus', models.CharField(max_length=100, verbose_name='город')),
                ('airport', models.CharField(max_length=100, verbose_name='airport')),
                ('international', models.BooleanField()),
                ('google_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
